// For formating text in HTM using tag with v-html
export const questions = {
    beforeProject: {
        letterToMyself: 'Where did Jac volunteer and when did he start?',
        englishTest: {
            listening: {
                Scenario1: {
                    question1: 'What is the person looking for?',
                    question2: 'Where is the train station?',
                    question3: 'Why is the person lost?',
                },
                Scenario2: {
                    question1: 'Where does Carla work?',
                    question2: 'Why does she enjoy her work?',
                    question3: 'What does Pierre do in the design department?',
                    question4: 'Which countries are Pierre and Carla from?',
                    question5: 'How many months will Pierre be working within the association?',
                },
                Scenario3: {
                    question1: 'Where is the director’s office?',
                    question2: 'How often does the general meeting take place?',
                    question3: 'How long does it last?',
                    question4: 'When do the activities start?',
                    question5: 'How long is the lunch break?',
                }
            },
            reading: {},                
            writting: {
                question1: 'Where did Jac volunteer and when did he start?',
                question2: 'What are the particularities of this country, geographically speaking?',
                question3: 'What happened in 2015? One correct answer.',
                question4: 'What are the other climate disasters that the country often faces? Several correct answers.',
                question5: 'Who did Jac work with during his volunteering experience?',
                question6: 'Name two missions that Jack had to carry out.',
            },
        },
        project: {
            advantages: {
                question1: 'Myadvantages & strengths',
                question2: 'Why do I think it is an advantage or a strength?',
                question3: 'My fears and challenges',
                question4: 'Please justify each answer',
            },
            expectations: {
                question1: 'I expect that everybody in the field take into account my experience',
                question2: 'I expect that after participating in this project I will find a job in my field',
                question3: 'I expect to develop/gain competences that will contribute to my professional, but also my personal development.',
                question4: 'I have no expectation, just wait and see',
                question5: 'To contribute to a piece of change in the local community in a specific sector and bring positive impact in the field',
                question6: 'To support the hosting organisation to improve its tools and/or methods of working in a specific field/with beneficiaries/ the staff’s technical competences',
                question7: 'Personally',
                question8: 'Professionally',
            },
            competences: {
                question1: 'Technical competences in a specific field (environment, health, pedagogy...other)',
                question2: 'Management competences (project implementation, fund raising, evaluation and monitoring, partnership relations...)',
                question3: 'Relational competences (diplomacy, intercultural issues management, team working...)',
                question4: 'Personal competences (autonomy, Adaptability, flexibility...)',
                question5: 'Other',
                question6: 'Technical competences',
                question7: 'Management competences',
                question8: 'Relational competences',
                question9: 'Network<br>I can bring new partners that:',
                question10: 'Personal competences',
                question11: 'Other',
            },
            howBenefit: {
                question1: 'In terms of career',
                question2: 'Personally',
                question3: 'Socially/relationships',
                question4: 'How can I make use of this experience when I return?',
            },
        },               
        country:{
            question1: '<b>Complete your information answering to the following questions: </b> <br> <ul><li>What are the country’s main resources, strengths?</li><li>What are the country’s main problems/challenges?</li><li>Main risks in the country and how you could mitigate them</li></ul>',
            question2: '<b>WHAT ARE THE MOST COMMON PRECONCEIVED NOTIONS ABOUT THE COUNTRY?</b> <br><ul><li> How to avoid the “saviour” thinking and mitigate stereotypes? </li><li> Do you have any preconceived ideas about your local country? Where did you get them from?</li><li> List three positive aspects about your hosting country, that makes it “different”.</li></ul>',
            question3: 'THE MAIN SPECIFIC FEATURES OF THE REGION AND THE LOCAL COMMUNITY WHERE MY MISSION WILL BE CONDUCTED:',
            question4: '<b> WORKING AND LIVING CONDITIONS</b><br> Here are the main questions to ask to your hosting organisation to avoid future conflict or disappointment. Check with your hosting organisation (HO) during a video meeting.',
            question5: '<h2>1. Logistics</h2> <br> Arrival arrangements: Arrival dates preferred/any dates to be avoided? <br><br> Transport from the origin country to the hosting country; transport from the airport to the accommodation. Please specify the name and contact of the person who will wait for you in the airport/train/bus station. Eventually, ask for a picture as well (mobile phone no – WhatsApp?)',
            question6: 'VISA: procedures for obtaining a VISA – required/provided documents. Are there any steps to follow, or registrations to make upon arrival in the country? If yes, what are required documents.',
            question7: 'Vaccination: any vaccination(s) is/are required to enter the country?',
            question8: 'Concerning the telephone package, do you know what is the best to do? : Will a mobile phone/SIM card be provided? Can I buy one at the airport?',
            question9: '2. Accommodation <br> Type of the accommodation provided (house, flat, hostel...), single, shared with other international volunteers/ local volunteers/ interns/ other staff members/host family. What are the rules of the accommodation (if you are going to live in the host country)? Equipment & facilities (internet, towels, bedsheets, fridge, washing machine...) location/address, transport means & stops to go from home to the airport/train station/office/field',
            question10: '3. Office<br>Which are the working conditions (working hours, days off, holidays/imposed holidays, computer, internet, etc.)?',
            question11: '4. Other locations where I need to carry out activities (in the field)',
            question12: '5. Transport<br>Monthly pass, foot walk, taxi, bicycle....',
            question13: '6. Day to day<br>Seasons & weather ... what to bring with me, law and regulations (drinking alcohol in public spaces...), living costs and cheap places to buy food...',
            question14: '7. Security in the country<br>How is the security in the country? (Streets? Dangerous zones? Etc.)',
            question15: '8. Project, role and responsibilities<br>Hosting organisation (location, aim, organigram, when possible, projects, how decisions are made)',
            question16: 'Your role and responsibilities in the project: which will be your mission and first activities',
            question17: 'Beneficiaries you will be working with - who will your project impact directly or indirectly?',
            question18: 'Resources: what resources are in place, available for the project you will be involved in; your planned activities.',
            question19: 'Network: is the organisation part of any network? How could you engage with different stakeholders?',
        },
        europeanUnion: {
            part1:{
                question1: 'What is the European Union?',
                question2: 'How does the European Union work?',
                question3: 'Find 3 key facts about the creation of the EU.',
                question4: 'What are the founding countries of the EU?',
                question5: 'What are the different symbols of the EU?',
                question6: 'How many member countries does the EU have?',
                question7: 'What is the day of Europe?',
                question8: 'Who is the current President of the European Parliament?',
                question9: 'Which countries are candidates to join the EU?',
                question10: 'What is the currency of the EU? What does it mean to you?',
            },
            part2:{
                question1: 'What does it mean to be a European citizen? Who can be considered a European citizen?',
                question2: 'What are the civil rights of a European citizen?', 
            },
            part3:{
                question1: 'Which European country produces 100% green electricity from renewable energy?',
                question2: 'Under the European Recovery Plan, what % of spending is dedicated to EU environmental objectives?',
                question3: 'Which EU Member State has made its public transport completely free of charge by 2020?',
                question4: 'Every 5 years, the EU sets targets for recycling. Two countries, European leaders in waste sorting, have already reached the 2025 target. These are:',
                question5: 'What eco-actions do you adopt in your daily life?',
                question6: 'How does your host country organize waste management? Is there a waste separation system?',
                question7: 'What are the eco-responsible acts put in place by the local population?',
                question8: 'What can you do to manage your (polluting) mailbox in an eco-responsible way?',
                question9: 'What are the different types of "green mobility" also called "soft" transport?',
                question10: 'What are the different types of "green mobility" in your host country/city?',
                question11: 'Find 3 positive and 3 negative aspects of "green mobility":',
                
            },
        },
        healthQuiz: {
            part1:{
                question1: 'On which website should I register to inform my country’s embassy of my mission dates abroad?',
                question2: 'Who do I need to inform of my presence when I get there? Where should I check in?',
                question3: 'Can I apply to a different embassy than the one in my country?',
                question4: 'In case of security problems, what should I do?',
            },
            part2:{
                question1: 'On which website can you search for news and important information about your host country?',
                question2: 'How to prepare your mission well?',
                question3: 'What can you do to keep yourself safe on a daily basis?',
                question4: 'Failure to follow safety measures for myself and others can lead to...',
                question5: 'How can I promote my integration in the host country? (Virtual mobility? Answer to this question: How can I promote my integration in the hosting organization and adapt myself to the local country in remote?)',
            },
            part3:{
                question1: 'Name the different ethnic groups present in the country? And is there any risk of of ethnic conflicts?',
                question2: 'What religions are practiced? And is there any risk of religious conflict?',
                question3: 'How can I adapt my behavior to the context of the host country? (Culture, religion, political regime, society, etc.)',
                question4: 'Are there any risks of natural disasters? If so, which ones?',
            },
            part4:{
                question1: 'What health-related steps should I take?',
                question2: 'What vaccinations are required before leaving for my host country?',
                question3: 'What should I have in my first aid kit?',
                question4: 'What should my emergency bag contain? (If you are advised to do so before your departure and depending on depending on the program and country of your mobility).',
                question5: 'What water can I drink in my host country? (Depending on the country and region)',
                question6: 'Hybrid/Virtual mobility? <br>How to have a balance between mobility and my personal life?',
                question7: 'What should I do if I’m ill during my virtual mobility? Who should I inform?',
            },
            part5:{
                question1: 'What insurance information do I need to know?',
                question2: 'When should I contact my insurance?',
                question3: 'Who should contact the insurance company in case of illness/accident?',
            },
            part6:{
                question1: 'Hello How are you ?<br>Good Bye<br>See you soon<br>Please<br>Thank you<br>Yes/No<br>Excuse-me I don’t speak (language of the country) ?<br>Do you speak (language of the country)?<br>Monday/Tuesday/Wednesday/Thursday/ Friday/Saturday/Sunday Yesterday / Today / Tomorrow<br>One / two / three / four /.... Ten Morning/Afternoon/Evening<br>Language of the host country',
                question2: 'My name is [name] and you? <br>I am a French intern/volunteer. <br>I work for [hoName].<br>Language of the host country',
                question3: 'Internet access <br>Where is [location]? <br>The bank <br>The doctor <br>The police <br>The pharmacy <br>The supermarket <br>I am thirsty/hungry <br>I am tired Fever/headache/stomach ache <br>I have a pain in ...<br>Language of the host country',
            },

        },
    },
    onProject: {
        activities: {
            question1: 'What are the main activities you are going to undertake?',
            question2: 'What kind of extra activities would you like to carry out, considering your personal project and initiatives? Are you aware of any interesting topic, activity, habit, etc that appeals to you in this country?',
        },
        management: {
            question1: 'Čo som sa naučil/a?',
            question2: 'Čo by som urobil/a inak?',
            question3: 'Čo by som urobil/a inak?',
        },
        followUp: {
            activities: {
                question1: 'What kind of activities have you been doing? Are you satisfied by the variety of the proposed activities?',
                question2: 'Do the tasks you are carrying out comply with your initial objectives?',
                question3: 'Do you consider any of the tasks inappropriate or irrelevant? Do all activities correspond to the agreement that you signed? Please specify and explain why.',
                question4: 'How do you feel about your tasks? Do you find them fulfilling?',
                question5: 'Do you face any challenges while accomplishing them? What is your favourite activity?',
                question6: 'Do the mission and the activities carried out enable you to be fully integrated into the team?',
                question7: 'Do the activities allow you to cooperate with local associations, local communities?',
                question8: 'How do you evaluate your relationship with the local team and with the beneficiary audience?',
                question9: 'Have you experienced any social or intercultural issues? If yes, give details and describe how you overcame them.',
                question10: 'How do you communicate with the team online?',
                question11: 'Does the online context impact your integration to the team?',
                question12: 'Can you pursue all the activities expected in a virtual context? How?',
                question13: 'How do you adapt to the virtual context? Does it enable you to take initiatives?',
                question14: 'Have you noticed any cultural difference on how online/virtual work is pursued in the host country?',
            },
            support: {
                question1: 'Do you feel like you are receiving adequate support from your sending and hosting organisations? What could be improved?',
                question2: 'Do you like your timetable, or would you rather change it? Is it manageable or not (in terms of time-management)?',
                question3: 'Do you feel that you are achieving the set objectives? How?',
                question4: 'Have you been able to meet regularly with your mentor / coordinator?',
                question5: 'Have you had any issues with your internet connection or your computer?',
                question6: 'Do you have any comments regarding your mentor or coordinator’s online follow-up?',
            },
            competences: {
                question1: 'Digital competences in different areas (management, communication, presentation…)',
                question2: 'Social media competences (Websites, Instagram, Facebook...)',
                question3: 'Technical competences in a specific field (construction, environment, health…)',
                question4: 'Management competences (project implementation, fund raising, evaluation and monitoring, partnership relations)',
                question5: 'Relational competences (diplomacy, intercultural issues management, team working)',
                question6: 'Personal competences (autonomy, adaptability, flexibility…)',
                question7: 'Have you noticed improvements on a personal level ever since you started your project?',
                question8: 'Did you learn or develop unexpected competences that you might have not in a traditional in-personal setting?',
                question9: 'Anything else you would like to mention:',
            },
        },
    },
    afterProject: {
        support: {
            question1: 'Did you receive any support from your sending organisation during the project?',
            question2: 'Did you receive any support from your hosting organisation during the project?',
            question3: 'DQuestion 3',
            question4: 'Was there any information that was missing?',
            question5: 'I received support from the sending organisation during the project.',
            question6: 'Where did Jac volunteer and when did he start?',
            question7: 'I received support from the hosting organisation during the project.',
            question8: 'What kind of support did I receive from my hosting organization (mentor/coordinator)?',
            question9: 'I had access to digital tools to work online.',
            question10: 'What kind of digital tools did I use (or were provided to me) to work online?',
            question11: 'I was able to adapt to working online.',
            question12: 'How did I adapt to working online?',
            question13: 'I received support during my virtual mobility.',
            question14: 'What kind of support did I receive during my virtual mobility?',
            question15: 'What needs to be improved in terms of support and guidance during the mobility project?',
        },
        tasks: {
            question1: 'I received adequate information about my tasks and activities.',
            question2: 'What were the activities planned and the activities I carried out (list)?',
            question3: 'I am satisfied with the activities I implemented.',
            question4: 'What were my most preferred activities/tasks and why?',
            question5: 'I had the necessary tools to implement my tasks.',
            question6: 'I am satisfied with how the online activities/tasks were organised.',
            question7: 'I was able to effectively manage the online activities.',
            question8: 'What activities/tasks I did not like and why?',
            question9: 'What would I change in the implementation of the activities?',
            question10: 'How was I able to overcome any obstacles/difficulties I faced in the implementation of the activities?',
            question11: 'What would I change in the support I received for the implementation of the activities?',
            question12: 'I am satisfied with the way I contributed to the activities.',
            question13: 'In which ways did I contribute to the implementation of the activities?',
            question14: 'I took initiatives.',
            question15: 'What kind of initiatives did I take (if any)? If I did not take any initiatives, why?',
            question16: 'The tasks/activities I implemented corresponded to what was included the learning agreement.',
            question17: 'I am satisfied with my online communication with the team during my virtual mobility.',
            question18: 'How did I collaborate with the team during the virtual mobility?',
            question19: 'Did the virtual context of my activities change my perspectives on intercultural communication? In what way?',
            question20: 'Did the virtual context of my mission add additional challenges to my integration, daily tasks, development of competences, and overall well-being? In what way?',
            question21: 'How could virtual mobilities be improved for future participants?',
           
        },
        competences: {
            question1: 'Digital competences in different areas (management, communication, presentation…)',
            question2: 'Social media competences (Websites, Instagram, Facebook...)',
            question3: 'Technical competences in a specific field (construction, environment, health…)',
            question4: 'Management competences (project implementation, fund raising, evaluation and monitoring, partnership relations)',
            question5: 'Relational competences (diplomacy, intercultural issues management, team working)',
            question6: 'Personal competences (autonomy, adaptability, flexibility…)',
            question7: 'Technical competences in a specific field (construction, environment, health…)',
            question8: 'Relational competences (diplomacy, intercultural issues management, team working...)',
            question9: 'Personal competences (autonomy, adaptability, flexibility…)',
            question10: 'Digital competences in different areas (management, communication, presentation…)',
            question11: 'Any other contributions?',
            question12: 'I am satisfied with my learning during this experience.',
            question13: 'I received support to gain insight on my competences from my mentor/line manager?',
            question14: 'To what extent were my learning objectives met?',
            question15: 'What helped me more in the development of competences?',
            question16: 'What are the competences I developed during the mobility that could support me in my future professional life?',            
        },
        general: {
            question1: 'I am satisfied with my overall experience.',
            question2: 'What do I take away from my mobility? How can it support me at a personal, social, and professional level in the future?',
            question3: 'What am I most proud of?',
            question4: 'the accommodation that was provided to me?',
            question5: 'the arrangements regarding local transportation?',
            question6: 'the arrangements regarding food?',
            question7: 'the digital tools provided to me for my activities online?',
            question8: 'the overall work of the sending organization',
            question9: 'the overall work of the hosting organization',
            question10: 'my overall contribution throughout the project',
            question11: 'I would recommend this experience to others.',
            question12: 'If I could do it again, what would I do differently?',
            question13: 'Any more suggestions/comments?',
            question14: 'What final score would I give to my own mobility?',

        },
    },
};




