export const volunteerDataModel = {
  basicInfo: {
    volunteerInfo: {
      name: '',
      surname: '',
      start: '',
      end: '',
      dateOfBirth: '',
      placeOfBirth: '',
      sex: '',
      address: '',
      telephone: '',
      email: '',
    },
    hoInfo: {
      hoName: '',
      hoAddress: '',
      projectNo: '',
      projectName: '',
      hoContactPerson: '',
      hoTelephone: '',
      hoEmail: '',
      hoWeb: '',
    },
    soInfo: {
      soName: '',
      soAddress: '',
      soContactPerson: '',
      soTelephone: '',
      soEmail: '',
      soWeb: '',
    },
  },
  beforeProject: {
    beforeProject: '',
    letterToMyself: '',
    europassCV: '',
    englishTest: {
      listening: {
        Scenario1: {
          question1: '',
          question2: '',
          question3: '',
        },
        Scenario2: {
          question1: '',
          question2: '',
          question3: '',
          question4: '',
          question5: '',
        },
        Scenario3: {
          question1: '',
          question2: '',
          question3: '',
          question4: '',
          question5: '',
        }
      },
      reading: {},
      writting: {},
    },
    languageLearning: '',
    project: '',
    country: {
      question1: '',
      question2: '',
      question3: '',
      question4: '',
      question5: '',
      question6: '',
      question7: '',
      question8: '',
      question9: '',
      question10: '',
      question11: '',
      question12: '',
      question13: '',
      question14: '',
      question15: '',
      question16: '',
      question17: '',
      question18: '',
      question19: '',
     },
    competences: '',
  },
  onProject: {
    onProject: '',
    roles: '',
    activities: {
      question1: '',
      question2: '',
    },
    management: {
      question1: '',
      question2: '',
      question3: '',
      question4: '',
    },
    followUp: {
      activities: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
        question7: '',
        question8: '',
        question9: '',
        question10: '',
        question11: '',
        question12: '',
        question13: '',
        question14: '',
      },
      support: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
      },
      competences: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
        question7: '',
        question8: '',
        question9: '',
      },
    },
  },
  afterProject: {
    afterProject: '',
  },
  userId: '',
  hasBasicInfo: '',
  };