export const volunteerDataModel = {
  basicInfo: {
    volunteerInfo: {
      name: '',
      surname: '',
      start: '',
      end: '',
      dateOfBirth: '',
      placeOfBirth: '',
      sex: '',
      address: '',
      telephone: '',
      email: '',
    },
    hoInfo: {
      hoName: '',
      hoAddress: '',
      projectNo: '',
      projectName: '',
      hoContactPerson: '',
      hoTelephone: '',
      hoEmail: '',
      hoWeb: '',
    },
    soInfo: {
      soName: '',
      soAddress: '',
      soContactPerson: '',
      soTelephone: '',
      soEmail: '',
      soWeb: '',
    },
  },
  beforeProject: {
    letterToMyself: '',
    europassCV: '',
    englishTest: {
      listening: {
        Scenario1: {
          question1: '',
          question2: '',
          question3: '',
        },
        Scenario2: {
          question1: '',
          question2: '',
          question3: '',
          question4: '',
          question5: '',
        },
        Scenario3: {
          question1: '',
          question2: '',
          question3: '',
          question4: '',
          question5: '',
        }
      },
      writting: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
      },
    },
    project: {
      advantages: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
      },
      expectations: {
        question1:{
          answer1: '',
          answer2: '',
          answer3: '',
        },
        question2: {
          answer1: '',
          answer2: '',
          answer3: '',
        },
        question3: {
          answer1: '',
          answer2: '',
          answer3: '',
        },
        question4: {
          answer1: '',
          answer2: '',
          answer3: '',
        },
        question5: {
          answer1: '',
          answer2: '',
          answer3: '',
        },
        question6: {
          answer1: '',
          answer2: '',
          answer3: '',
        },
        question7: '',
        question8: '',
      },
      competences: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
        question7: '',
        question8: '',
        question9: '',
        question10: '',
        question11: '',
      },
      howBenefit: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
      },
    },
    country: {
      question1: '',
      question2: '',
      question3: '',
      question4: '',
      question5: '',
      question6: '',
      question7: '',
      question8: '',
      question9: '',
      question10: '',
      question11: '',
      question12: '',
      question13: '',
      question14: '',
      question15: '',
      question16: '',
      question17: '',
      question18: '',
      question19: '',
    },
    competences: '',
    europeanUnion: {
      part1: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
        question7: '',
        question8: '',
        question9: '',
        question10: '',
      },
      part2: {
        question1: '',
        question2: '',
      },
      part3: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',   
        question6: '',
        question7: '',
        question8: '',
        question9: '',
        question10: '',
        question11: '',
      },
    },
    healthQuiz: {
      part1: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
      },
      part2: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
      },
      part3: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
      },
      part4: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
        question7: '',
      },
      part5: {
        question1: '',
        question2: '',
        question3: '',
      },
      part6: {
        question1: '',
        question2: '',
        question3: '',
      },
    },
    checklist: '',

  },
  onProject: {     
    activities: {
      question1: '',
      question2: '',
    },
    management: {
        question1: '',
        question2: '',
        question3: '',
  },
    followUp: {
      activities: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
        question7: '',
        question8: '',
        question9: '',
        question10: '',
        question11: '',
        question12: '',
        question13: '',
        question14: '',
      },
      support: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
      },
      competences: {
        question1: '',
        question2: '',
        question3: '',
        question4: '',
        question5: '',
        question6: '',
        question7: '',
        question8: '',
        question9: '',
      },

    },
  },
  afterProject: {
    afterProject: '',
    support: {
      question1: '',
      question2: '',
      question3: '',
      question4: '',
      question5: '',
      question6: '',
      question7: '',
      question8: '',
      question9: '',
      question10: '',
      question11: '',
      question12: '',
      question13: '',
      question14: '',
      question15: '',
    },
    tasks: {
      question1: '',
      question2: '',
      question3: '',
      question4: '',
      question5: '',
      question6: '',
      question7: '',
      question8: '',
      question9: '',
      question10: '',
      question11: '',
      question12: '',
      question13: '',
      question14: '',
      question15: '',
      question16: '',
      question17: '',
      question18: '',
      question19: '',
      question20: '',
      question21: '',
    },
    competences: {
      question1: '',
      question2: '',
      question3: '',
      question4: '',
      question5: '',
      question6: '',
      question7: '',
      question8: '',
      question9: '',
      question10: '',
      question11: '',
      question12: '',
      question13: '',
      question14: '',
      question15: '',
      question16: '',
    },
    general: {
      question1: '',
      question2: '',
      question3: '',
      question4: '',
      question5: '',
      question6: '',
      question7: '',
      question8: '',
      question9: '',
      question10: '',
      question11: '',
      question12: '',
      question13: '',
      question14: '',
    },
  },
  userId: '',
  hasBasicInfo: '',
  };