export const volunteerDataModel = {
  basicInfo: {
    volunteerInfo: {
      name: '',
      surname: '',
      start: '',
      end: '',
      dateOfBirth: '',
      placeOfBirth: '',
      sex: '',
      address: '',
      telephone: '',
      email: '',
    },
    hoInfo: {
      hoName: '',
      hoAddress: '',
      projectNo: '',
      projectName: '',
      hoContactPerson: '',
      hoTelephone: '',
      hoEmail: '',
      hoWeb: '',
    },
    soInfo: {
      soName: '',
      soAddress: '',
      soContactPerson: '',
      soTelephone: '',
      soEmail: '',
      soWeb: '',
    },
  },
  beforeProject: {
    beforeProject: '',
    letterToMyself: '',
    europassCV: '',
    englishTest: '',
    languageLearning: '',
    project: '',
    country: '',
    competences: '',
  },
  onProject: {
    onProject: '',
  },
  afterProject: {
    afterProject: '',
  },
  userId: '',
  hasBasicInfo: '',
  };